#!/usr/bin/env bash
set -euo pipefail

# Generates `frontend/src/deploy/bytecode.generated.ts` from Foundry artifacts.
#
# This file is used by the frontend (CREATE2 address prediction) and by Foundry
# scripts (e.g. seeding the UniversalBytecodeStore).
#
# Usage:
#   ./script/generate_frontend_deploy_bytecode.sh

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="$ROOT_DIR/frontend/src/deploy/bytecode.generated.ts"

cd "$ROOT_DIR"

echo "Generating deploy bytecode → frontend/src/deploy/bytecode.generated.ts"

# Ensure artifacts are up to date.
forge build >/dev/null

bytecode() {
  # Prints creation bytecode (0x...). Use last line in case warnings appear.
  forge inspect "$1" bytecode | tail -n 1
}

cat >"$OUT_FILE" <<'EOF'
// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
// Generated by: script/generate_frontend_deploy_bytecode.sh
//
// This file contains contract *creation bytecode* required for Phase-2 AA (CREATE2) deployments.

export const DEPLOY_BYTECODE = {
EOF

printf "  CreatorOVault: '%s',\n" "$(bytecode CreatorOVault)" >>"$OUT_FILE"
printf "  CreatorOVaultWrapper: '%s',\n" "$(bytecode CreatorOVaultWrapper)" >>"$OUT_FILE"
printf "  CreatorShareOFT: '%s',\n" "$(bytecode CreatorShareOFT)" >>"$OUT_FILE"
printf "  OFTBootstrapRegistry: '%s',\n" "$(bytecode OFTBootstrapRegistry)" >>"$OUT_FILE"
printf "  CreatorGaugeController: '%s',\n" "$(bytecode CreatorGaugeController)" >>"$OUT_FILE"
printf "  CCALaunchStrategy: '%s',\n" "$(bytecode CCALaunchStrategy)" >>"$OUT_FILE"
printf "  CreatorOracle: '%s',\n" "$(bytecode CreatorOracle)" >>"$OUT_FILE"

cat >>"$OUT_FILE" <<'EOF'
} as const;
EOF

echo "Done."

