export { Home } from './Home'
export { Dashboard } from './Dashboard'
export { Vault } from './Vault'
export { CompleteAuction } from './CompleteAuction'
export { ActivateAkita } from './ActivateAkita'
export { AuctionBid } from './AuctionBid'
export { default as GaugeVoting } from './GaugeVoting'
